version: "3.9"

services:
  api:
    # Use the image built and pushed in the CI pipeline
    image: ${DOCKER_IMAGE_NAME}:${BUILD_TAG:-latest}
    container_name: liemlan_api_dev
    restart: always
    ports:
        # Map host port to container port
      - "${HOST_PORT}:3000"
    env_file:
      # Config in server environment
      - .env.dev